name: AtomicReports
main: ConstructStudios\Report\Report
api: 3.0.0
version: 0.1
author: Based on ConstructStudios' ReportSystem. Forked and edited by YoYo

softdepend:
  - PixelgamesToDiscord

permissions:
  reportsystem.admin:
    description: AdminUI (Handle Reports)
    default: op
